// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DVSE.Web.HolidayManagement.Controllers
{
    public partial class ManagementController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ManagementController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditEmployee()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEmployee);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetHolidaysForEmployee()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetHolidaysForEmployee);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditHolidayPeriod()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditHolidayPeriod);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CancelHolidayPeriod()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelHolidayPeriod);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UndoCancelHolidayPeriod()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UndoCancelHolidayPeriod);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOverviewForEmployee()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOverviewForEmployee);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ManagementController Actions { get { return MVC.Management; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Management";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Management";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetEmployees = "GetEmployees";
            public readonly string EditEmployee = "EditEmployee";
            public readonly string GetHolidaysForEmployee = "GetHolidaysForEmployee";
            public readonly string EditHolidayPeriod = "EditHolidayPeriod";
            public readonly string CancelHolidayPeriod = "CancelHolidayPeriod";
            public readonly string UndoCancelHolidayPeriod = "UndoCancelHolidayPeriod";
            public readonly string GetOverviewForEmployee = "GetOverviewForEmployee";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetEmployees = "GetEmployees";
            public const string EditEmployee = "EditEmployee";
            public const string GetHolidaysForEmployee = "GetHolidaysForEmployee";
            public const string EditHolidayPeriod = "EditHolidayPeriod";
            public const string CancelHolidayPeriod = "CancelHolidayPeriod";
            public const string UndoCancelHolidayPeriod = "UndoCancelHolidayPeriod";
            public const string GetOverviewForEmployee = "GetOverviewForEmployee";
        }


        static readonly ActionParamsClass_EditEmployee s_params_EditEmployee = new ActionParamsClass_EditEmployee();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditEmployee EditEmployeeParams { get { return s_params_EditEmployee; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditEmployee
        {
            public readonly string id = "id";
            public readonly string employeeVM = "employeeVM";
        }
        static readonly ActionParamsClass_GetHolidaysForEmployee s_params_GetHolidaysForEmployee = new ActionParamsClass_GetHolidaysForEmployee();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetHolidaysForEmployee GetHolidaysForEmployeeParams { get { return s_params_GetHolidaysForEmployee; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetHolidaysForEmployee
        {
            public readonly string id = "id";
            public readonly string forCurrentYear = "forCurrentYear";
        }
        static readonly ActionParamsClass_EditHolidayPeriod s_params_EditHolidayPeriod = new ActionParamsClass_EditHolidayPeriod();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditHolidayPeriod EditHolidayPeriodParams { get { return s_params_EditHolidayPeriod; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditHolidayPeriod
        {
            public readonly string holidayPeriodVM = "holidayPeriodVM";
        }
        static readonly ActionParamsClass_CancelHolidayPeriod s_params_CancelHolidayPeriod = new ActionParamsClass_CancelHolidayPeriod();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CancelHolidayPeriod CancelHolidayPeriodParams { get { return s_params_CancelHolidayPeriod; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CancelHolidayPeriod
        {
            public readonly string id = "id";
            public readonly string note = "note";
        }
        static readonly ActionParamsClass_UndoCancelHolidayPeriod s_params_UndoCancelHolidayPeriod = new ActionParamsClass_UndoCancelHolidayPeriod();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UndoCancelHolidayPeriod UndoCancelHolidayPeriodParams { get { return s_params_UndoCancelHolidayPeriod; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UndoCancelHolidayPeriod
        {
            public readonly string id = "id";
            public readonly string note = "note";
        }
        static readonly ActionParamsClass_GetOverviewForEmployee s_params_GetOverviewForEmployee = new ActionParamsClass_GetOverviewForEmployee();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOverviewForEmployee GetOverviewForEmployeeParams { get { return s_params_GetOverviewForEmployee; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOverviewForEmployee
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Employee = "_Employee";
                public readonly string _HolidayPeriod = "_HolidayPeriod";
                public readonly string Index = "Index";
            }
            public readonly string _Employee = "~/Views/Management/_Employee.cshtml";
            public readonly string _HolidayPeriod = "~/Views/Management/_HolidayPeriod.cshtml";
            public readonly string Index = "~/Views/Management/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ManagementController : DVSE.Web.HolidayManagement.Controllers.ManagementController
    {
        public T4MVC_ManagementController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void GetEmployeesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult GetEmployees()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetEmployees);
            GetEmployeesOverride(callInfo);
            return callInfo;
        }

        partial void EditEmployeeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult EditEmployee(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEmployee);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditEmployeeOverride(callInfo, id);
            return callInfo;
        }

        partial void EditEmployeeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DVSE.Web.HolidayManagement.Models.EmployeeViewModel employeeVM);

        public override System.Web.Mvc.ActionResult EditEmployee(DVSE.Web.HolidayManagement.Models.EmployeeViewModel employeeVM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEmployee);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "employeeVM", employeeVM);
            EditEmployeeOverride(callInfo, employeeVM);
            return callInfo;
        }

        partial void GetHolidaysForEmployeeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, bool forCurrentYear);

        public override System.Web.Mvc.ActionResult GetHolidaysForEmployee(int id, bool forCurrentYear)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetHolidaysForEmployee);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "forCurrentYear", forCurrentYear);
            GetHolidaysForEmployeeOverride(callInfo, id, forCurrentYear);
            return callInfo;
        }

        partial void EditHolidayPeriodOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DVSE.Web.HolidayManagement.Models.HolidayPeriodViewModel holidayPeriodVM);

        public override System.Web.Mvc.ActionResult EditHolidayPeriod(DVSE.Web.HolidayManagement.Models.HolidayPeriodViewModel holidayPeriodVM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditHolidayPeriod);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "holidayPeriodVM", holidayPeriodVM);
            EditHolidayPeriodOverride(callInfo, holidayPeriodVM);
            return callInfo;
        }

        partial void CancelHolidayPeriodOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string note);

        public override System.Web.Mvc.ActionResult CancelHolidayPeriod(int id, string note)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelHolidayPeriod);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "note", note);
            CancelHolidayPeriodOverride(callInfo, id, note);
            return callInfo;
        }

        partial void UndoCancelHolidayPeriodOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string note);

        public override System.Web.Mvc.ActionResult UndoCancelHolidayPeriod(int id, string note)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UndoCancelHolidayPeriod);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "note", note);
            UndoCancelHolidayPeriodOverride(callInfo, id, note);
            return callInfo;
        }

        partial void GetOverviewForEmployeeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult GetOverviewForEmployee(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOverviewForEmployee);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetOverviewForEmployeeOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
